config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    get 'users/sign_in' => 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :business, path: :b do
    resources :users
    
    authenticated :user, lambda {|u| u.type == "Business"} do
      root :to => "home#index"
    end
  end

  namespace :individual, path: :i do
    resources :users do
      resources :connections
      resources :portfolios, only: [:index]
      get '/portfolio' => 'portfolios#show'
      post '/profile/update_display_information' => 'profile#update_display_information'
      put '/profile/update' =>'profile#update'
      get '/profile/edit' =>'profile#edit'
      get '/profile' =>'profile#show'
    end

    authenticated :user, lambda {|u| u.type == "Individual" ||  u.type == "ArtEnthusiast"} do
      root to: "home#index"
    end
  end

  namespace :admin do
    resources :users
    
    authenticated :user, lambda {|u| u.type == "Admin"} do
      root :to => "home#index"
    end
  end  
  
  root :to => 'home#index'

end

app/models/individual.rb
class Individual < User
end

app/controllers/individual/connections_controller.rb
class Individual::ConnectionsController < ApplicationController
	layout 'individual'

	def index
		@contacts = current_user.contacts
	end

end

app/controllers/individual/home_controller.rb
class Individual::HomeController < ApplicationController
	layout 'individual'
	
end

app/controllers/individual/portfolios_controller.rb
class Individual::PortfoliosController < ApplicationController
	layout 'individual'
	
end

app/controllers/individual/profile_controller.rb
class Individual::ProfileController < ApplicationController
	layout 'individual'
	skip_before_action :verify_authenticity_token, only: [:update_display_information																																																																																																																																																																																									]

	def edit
		@display_information = current_user.display_information || current_user.build_display_information
	end

	def update
		current_user.update!(profile_params)
		redirect_to individual_user_profile_path(current_user)
	end

	def update_display_information
		dp = DisplayInformation.find_or_initialize_by(user_id: current_user.id)
		dp.profile_photo = profile_photo_params[:profile_photo].present? ? profile_photo_params[:profile_photo] : nil
		dp.save!

		render partial: '/layouts/common/upload_profile_photo'
	end

	private

	def profile_params
		params.require(current_user.parameterized_type.to_sym).permit(display_information_attributes: [:id, :title, :summary], 
			organizations_attributes: [:id, :name, :affiliation, :start_date, :end_date, :organization_type,
			:designation, :_destroy])
	end

	def profile_photo_params
		params.require(:display_information).permit(:profile_photo, :id)
	end

end

app/views/individual/profile/_organization_fields.html.erb
<div class="fields">
	<%= f.text_field :name, placeholder: 'Organization Name' %><span class='asterisk'></span>
	<%= f.text_field :designation, placeholder: 'Designation' %><span class='asterisk'></span>
	<%= f.text_field :affiliation, placeholder: 'Affiliation/University' %>
	<%= f.date_field :start_date, placeholder: 'Start Date' %>
	<%= f.date_field :end_date, placeholder: 'End Date' %>
	<% if defined? org_type %>
		<%= f.hidden_field :organization_type, value: org_type %>
	<% else %>
		<%= f.hidden_field :organization_type %>
	<% end %>
	<%= f.hidden_field :_destroy %>
	<%= link_to_remove_fields "<span class='glyphicon glyphicon-minus'></span>".html_safe, f %>
</div>

app/views/individual/profile/edit.html.erb
<div class="col-sm-offset-3 col-md-offset-2 main">
	<%= form_for current_user, url: individual_user_profile_update_path(current_user), method: :put, id: 'profile_form' do |f| %>
	  <div class='btn-container'>
		  <%= f.submit 'Done', class: 'edit_profile btn btn-default' %>
		  <%= link_to 'Back', individual_user_profile_path(current_user), class: 'edit_profile btn btn-default'%>
		</div>
		<div class="clear"></div>

		<div class="profile_container">
			<div class="row">
				<div class="summary_block">
					<%= f.fields_for :display_information do |builder| %>
						<h4>Title</h4> 
						<%= builder.text_field :title, class: 'title', autofocus: true %>
						<div class="clear"></div>
						<h4>Summary</h4>
						<%= builder.text_area :summary, class: 'summary' %>
					<% end %>
				</div>
			</div>
		  <div class="row">
			  <h4 class='profile_block' id='education_block'>Education <span class="glyphicon glyphicon-menu-up"></span></h4>
	  		<div class="education_block profile_sub_block">
	        <%= f.fields_for :organizations do |builder| %>
            <%= render 'organization_fields', f: builder %>
			  	<% end if current_user.education_details.present? %>
          <%= link_to_add_fields "<span class='glyphicon glyphicon-plus'></span> Add New".html_safe, f, :organizations, 'school' %>
	  		</div>
		  </div>
		  <div class="row">
			  <h4 class='profile_block' id="experience_block">Experience <span class="glyphicon glyphicon-menu-up"></span></h4>
			  <div class="experience_block profile_sub_block">
	        <%= f.fields_for :organizations do |builder| %>
	          <%= render 'organization_fields', f: builder %>
			  	<% end if current_user.experience.present? %>
	        <%= link_to_add_fields "<span class='glyphicon glyphicon-plus'></span> Add New".html_safe, f, :organizations, 'company' %>
				</div>
		  </div>
		  <div class="row">
			  <h4 class='profile_block' id="cources_block" >Courses <span class="glyphicon glyphicon-menu-up"></span></h4>
			  <span class="text-muted">Something else</span>
		  </div>
		  <div class="row">
			  <h4 class='profile_block' id="skills_block" >Skills <span class="glyphicon glyphicon-menu-up"></span></h4>
			  <span class="text-muted">Something else</span>
		  </div>
		</div>
	<% end %>
</div>

app/views/individual/profile/show.html.erb
<div class="col-sm-offset-3 col-md-offset-2 main">
	<div class='btn-container'>
		<%= link_to 'Edit', individual_user_profile_edit_path, class: 'edit_profile btn btn-default'%>
	</div>
	<div class="clear"></div>

	<div class="profile_container">
	 	<div class="row">
			<div class="summary_block">
				<h4>Title</h4> <fieldset class='title'><%= current_user.display_information.title rescue '-'%></fieldset>
				<div class="clear"></div>
				<h4>Summary</h4> <fieldset class='summary'><%= current_user.display_information.summary rescue '-'%></fieldset>
			</div>
	  </div>
	  <div class="row">
		  <h4 class='profile_block' id='education_block'>Education <span class="glyphicon glyphicon-menu-up"></span></h4>
	  		<div class="education_block profile_sub_block">
			  	<ul>
				  	<% current_user.education_details.each do |edu|%>
			  			<li>
					  		<label>School/College:</label> <span><%= edu.name || '-'%></span>
					  		<label>University:</label> <span><%= edu.affiliation || '-'%></span>
					  		<label>Duration:</label> <span><%= ("#{edu.start_date} - #{edu.end_date}") %></span>
			  			</li>
			  			<div class="clear"></div>
				  	<% end %>
			  	</ul>
	  		</div>
	  </div>
	  <div class="row">
		  <h4 class='profile_block' id="experience_block">Experience <span class="glyphicon glyphicon-menu-up"></span></h4>
		  <div class="experience_block profile_sub_block">
		  	<ul>
			  	<% current_user.experience.each do |org|%>
		  			<li>
				  		<label>Organization:</label> <span><%= org.name || '-'%></span>
				  		<label>Designation:</label> <span><%= org.designation || '-'%></span>
				  		<label>Duration:</label> <span><%= "#{org.start_date} - #{org.end_date}" %></span>
		  			</li>
		  			<div class="clear"></div>
			  	<% end %>
		  	</ul>
			</div>
	  </div>
	  <div class="row">
		  <h4 class='profile_block' id="cources_block" >Courses <span class="glyphicon glyphicon-menu-up"></span></h4>
		  <span class="text-muted">Something else</span>
	  </div>
	  <div class="row">
		  <h4 class='profile_block' id="skills_block" >Skills <span class="glyphicon glyphicon-menu-up"></span></h4>
		  <span class="text-muted">Something else</span>
	  </div>
	</div>
</div>