config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    get 'users/sign_in' => 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :business, path: :b do
    resources :users
    
    authenticated :user, lambda {|u| u.type == "Business"} do
      root :to => "home#index"
    end
  end

  namespace :individual, path: :i do
    resources :users do
      resources :connections
      resources :portfolios, only: [:index]
      get '/portfolio' => 'portfolios#show'
      post '/profile/update_display_information' => 'profile#update_display_information'
      put '/profile/update' =>'profile#update'
      get '/profile/edit' =>'profile#edit'
      get '/profile' =>'profile#show'
    end

    authenticated :user, lambda {|u| u.type == "Individual" ||  u.type == "ArtEnthusiast"} do
      root to: "home#index"
    end
  end

  namespace :admin do
    resources :users
    
    authenticated :user, lambda {|u| u.type == "Admin"} do
      root :to => "home#index"
    end
  end  
  
  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base

	has_many :users
	validates :name, presence: true

	def self.default
		find_by(name: 'free')
	end

	def is_trail?
		return true if name == 'trial'
	end

	def is_free?
		return true if name == 'free'
	end

	def is_premium?
		return true if name == 'premium'
	end

end

app/models/admin.rb
class Admin < User
end

app/models/art_enthusiast.rb
class ArtEnthusiast < User
end

app/models/business.rb
class Business < User
end

app/models/category.rb
class Category < ActiveRecord::Base

	def titleized_name
		name.titleize
	end
end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :user
	belongs_to :contact, class_name: 'User'

	validates :contact_id, uniqueness: {scope: :user_id}
end

app/models/display_information.rb
class DisplayInformation < ActiveRecord::Base
	self.table_name = 'display_information'
	
	has_attached_file :profile_photo
	validates_attachment :profile_photo, 
		content_type: { content_type: [/image/] }

	belongs_to :user
	
end

app/models/document.rb
class Document < ActiveRecord::Base

belongs_to :documentable, polymorphic: true

has_attached_file :doc_file
validates_attachment :doc_file, presence: true


def documentable_type=(the_type)
	super(the_type.to_s.classify.constantize.base_class.to_s)
end

end

app/models/individual.rb
class Individual < User
end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :users
  has_many :projects
  
  validates :organization_type, inclusion: {in: ['school', 'company']}
  validates :start_date, :end_date, :user_id, presence: true
  
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :users
	belongs_to :organization
end

app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

app/models/training.rb
class Training < ActiveRecord::Base
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :type, :category_id, :first_name, :last_name, :email, :account_id, presence: true

  belongs_to :account
  has_many :documents, as: :documentable, dependent: :destroy
  has_many :organizations, dependent: :destroy
  has_one :display_information, dependent: :destroy

  has_many :connections
  has_many :trainings
  has_many :contacts, through: :connections
  has_many :inverse_connections, class_name: "Connection", foreign_key: "contact_id"
  has_many :inverse_contacts, through: :inverse_connections, source: :user

  accepts_nested_attributes_for :organizations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_information, reject_if: :all_blank, allow_destroy: true

  def full_name
  	"#{first_name} #{last_name}".titleize 
  end

  def parameterized_type
    return 'art_enthusiast' if type == 'ArtEnthusiast'
    return type.parameterize
  end

  def education_details
  	organizations.where(organization_type: 'school')
  end

  def experience
  	organizations.where(organization_type: 'company')
  end

  def display_picture
    display_information.profile_photo.url rescue nil
  end

  def display_title
    display_information.title rescue '-'
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	layout 'admin'
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  before_filter :configure_permitted_parameters, if: :devise_controller?


  def layout_by_resource
  	if devise_controller? && [:new, :create].include?(action_name.to_sym)
      'home'
  	end
  end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up,) { |u| u.permit(:first_name, :last_name, :type, :dob, :phone, :category_id, :account_id, :email,
                    :current_password, :password, :password_confirmation) }
  end

  def after_sign_in_path_for(resource)
    return individual_root_path if resource.type.downcase == 'individual' || resource.type.downcase == 'artenthusiast'
    return business_root_path if resource.type.downcase == 'business'
    return admin_root_path if resource.type.downcase == 'admin'
    return root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/business/home_controller.rb
class Business::HomeController < ApplicationController
	layout 'business'
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'

	# before_action :authenticate_user!
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_add_fields(name, f, association, org_type=nil)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder, org_type: org_type )
    end

    link_to(name, '#', class: 'add_fields btn', data: { id: id, fields: fields.gsub('\n', '') })
  end

  def link_to_remove_fields(name, f)
  	link_to(name, '#', class: 'remove_fields')      
  end

end

app/views/layouts/admin.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>CreoYou Home</title>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag 'common' %>
    <%= stylesheet_link_tag 'common', 'individual' %>
  </head>

  <body class="">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CreoYou</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :get %></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Creoyou</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "common" %>
</head>
<body>
<div id="main-container" class="container">
	<div class="row">
		<div id="sidebar" class="col-xs-3">
        	<h3>Creative You</h3>
        </div>
		<div id="content" class="col-xs-9">
        	<%= yield %>
        </div>
	</div>
</div>
</body>
</html>

app/views/layouts/common/_sidelinks_individual.html.erb
  <div class="col-sm-3 col-md-2 sidebar">
		<%= link_to 'javascript:void(0)', class: 'edit_display_pic' do %>
	 		<span class='glyphicon glyphicon-edit'></span>
		<% end %>
  	<div class='display_pic'>
  		<%= render 'layouts/common/upload_profile_photo'%>
  	</div>
  	<div class='display_info'>
  		<div class="summary_block">
				<div class='title'><span class='glyphicon glyphicon-pencil'></span>
					<%= current_user.full_name rescue '-'%>
				</div>
				<div class="clear"></div>
				<div class='summary'><span class='glyphicon glyphicon-pencil'></span>
					<%= current_user.display_information.title rescue '-'%>
				</div>
			</div>
  	</div>
	  <ul class="nav nav-sidebar">
	    <li class="active"><%= link_to 'Home', individual_root_path %></li>
	    <li><%= link_to 'About Me', individual_user_profile_path(current_user) %></li>
	    <li><%= link_to 'Portfolio', individual_user_portfolios_path(current_user) %></li>
	    <li><%= link_to 'Connections', individual_user_connections_path(current_user) %></li>
	    <li><a href="#">Events</a></li>
	  </ul>
	</div>

app/views/layouts/common/_upload_profile_photo.html.erb
<!-- <div class='display_pic'> -->
	<%= form_for :display_information, url: individual_user_profile_update_display_information_path(current_user), html: {id: 'display_information_update_form', multipart: true} do |f| %>
		<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
		<%= image_tag current_user.display_picture, size: "137x137", alt: '' %>
		<!-- <img src="/assets/bottom_banner_img_640.jpg"> -->
		<div class='btn-options'>
			<div class="fileUpload">
				<%= f.hidden_field :update_path, value: individual_user_profile_update_display_information_path(current_user) %>
				<%= f.file_field :profile_photo, class: 'choose_file', id: 'choose_display_pic' %>
			</div>
			<%= link_to '<span class="glyphicon glyphicon-trash">'.html_safe, 'javascript:void(0)', class: 'remove_file' %>
			<%= link_to "<span class='glyphicon glyphicon-remove'>".html_safe, 'javascript:void(0)', class: 'close_options' %>
		</div>
	<% end %>
<!-- </div> -->

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Creoyou</title>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', 'common', 'home' %>
  </head>

  <body>
    <div class="container">
      <!-- The justified navigation menu is meant for single line per list item.
           Multiple lines will require custom code not provided by Bootstrap. -->
      <div class="masthead">
        <h3 class="text-muted">Creoyou</h3>
        <nav>
          <ul class="nav nav-justified">
            <li class="active"><%= link_to 'Home', root_path %></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li>
              <% if current_user.present? %>
                <%= link_to 'Logout', destroy_user_session_path, method: :get %>
              <% else %>
                <%= link_to 'Login', new_user_session_path %>
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
      
      <%= yield %>

      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug 
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    -->
  </body>
</html>

app/views/layouts/individual.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>CreoYou Home</title>
    <%= javascript_include_tag 'application', 'common', 'individual/includes' %>
    <%= stylesheet_link_tag 'application', 'common', 'individual' %>
  </head>

  <body class="">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CreoYou</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a> Hi <%= current_user.full_name %></a></li>
            <li><a href="#">Settings</a></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :get %></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid individual-container">
      <!-- <div class=""> -->
        <%= render 'layouts/common/sidelinks_individual' %>
        <%= yield %>
      <!-- </div> -->
    </div>

  </body>
</html>